name: Cookbook
main: ca.celticminstrel.cookbook.Cookbook
version: 1.0.1-exphc
author: Celtic Minstrel
permissions:
  cookbook.view:
    description: Allows you to view the in-game cookbook window.
    default: true
