name: Cookbook
main: ca.celticminstrel.cookbook.Cookbook
version: 0.7
author: Celtic Minstrel
softdepend: [Spout]
permissions:
  cookbook.view:
    description: Allows you to view the in-game cookbook window.
    default: true